export const navItem = [
    { id: 1, title: 'Jobs', path: '#' },
    { id: 2, title: 'Companies', path: '#' },
    { id: 3, title: 'Services', path: '#' }
]

export const Jobs = [
    { id: 'j1', title: 'Popular categories', path: '#' },
    { id: 'j2', title: 'Jobs in demand', path: '#' },
    { id: 'j3', title: 'Jobs by location', path: '#' },
    { id: 'j4', title: 'Explore more jobs', path: '#' },
    { id: 1, title: 'IT jobs', path: '#' },
    { id: 7, title: 'Fresher jobs', path: '#' },
    { id: 13, title: 'Jobs in Delhi', path: '#' },
    { id: 19, title: 'Jobs by category', path: '#' },
    { id: 2, title: 'Sales jobs', path: '#' },
    { id: 8, title: 'MNC jobs', path: '#' },
    { id: 14, title: 'Jobs in Mumbai', path: '#' },
    { id: 20, title: 'Jobs by skill', path: '#' },
    { id: 3, title: 'Marketing jobs', path: '#' },
    { id: 9, title: 'Remote jobs', path: '#' },
    { id: 15, title: 'Jobs in Bangalore', path: '#' },
    { id: 21, title: 'Jobs by location', path: '#' },
    { id: 4, title: 'Data Science jobs', path: '#' },
    { id: 10, title: 'Work from home jobs', path: '#' },
    { id: 16, title: 'Jobs in Hyderabad', path: '#' },
    { id: 22, title: ' Jobs by designation', path: '#' },
    { id: 5, title: 'HR jobs', path: '#' },
    { id: 11, title: 'Walk -in jobs', path: '#' },
    { id: 17, title: 'Jobs in Chennai', path: '#' },
    { id: 23, title: 'Create free job alert', path: '#' },
    { id: 6, title: ' Engineering jobs', path: '#' },
    { id: 12, title: 'Part - time jobs', path: '#' },
    { id: 18, title: 'Jobs in Pune', path: '#' },
    { id: 19, title: ' ', path: '#' }
]

export const Companies = [
    { id: 'c1', title: 'Explore categories', path: '#' },
    { id: 'c2', title: 'Explore collections', path: '#' },
    { id: 'c3', title: 'Research companies', path: '#' },
    { id: '-1', title: 'by 🟣 Ambitionbox', path: '#' },
    { id: 1, title: 'Unicorn', path: '#' },
    { id: 6, title: 'Top companies', path: '#' },
    { id: 11, title: 'Interview questions', path: '#' },
    { id: 0, title: '', path: '#' },
    { id: 2, title: 'MNC', path: '#' },
    { id: 7, title: 'IT companies', path: '#' },
    { id: 12, title: 'Company salaries', path: '#' },
    { id: -1, title: '', path: '#' },
    { id: 3, title: 'Startup', path: '#' },
    { id: 8, title: 'Fintech companies', path: '#' },
    { id: 13, title: 'Company reviews', path: '#' },
    { id: 0, title: '', path: '#' },
    { id: 4, title: 'Product based', path: '#' },
    { id: 9, title: 'Sponsored companies', path: '#' },
    { id: 14, title: 'Salary Calculator', path: '#' },
    { id: 0, title: '', path: '#' },
    { id: 5, title: 'Internet', path: '#' },
    { id: 10, title: 'Featured companies', path: '#' },
    { id: 11, title: '', path: '#' },
    { id: 0, title: '', path: '#' },
    { id: 0, title: '', path: '#' }

]

export const Services = [
    { id: 's1', title: 'Resume writing', path: '#' },
    { id: 's3', title: `Get recruiter's attention`, path: '#' },
    { id: 's5', title: 'Learn & upskill', path: '#' },
    { id: 's6', title: ' Free resume resources', path: '#' },
    { id: 1, title: 'Text resume', path: '#' },
    { id: 7, title: ' Resume display', path: '#' },
    { id: 11, title: 'Data Science courses', path: '#' },
    { id: 19, title: ' Resume maker for freshers', path: '#' },
    { id: 2, title: 'Visual resume', path: '#' },
    { id: 8, title: ' Recruiter connection', path: '#' },
    { id: 12, title: 'Technology courses', path: '#' },
    { id: 20, title: 'Resume quality score', path: '#' },
    { id: 3, title: 'Resume critique', path: '#' },
    { id: 9, title: 'Job search booster', path: '#' },
    { id: 13, title: 'Management courses', path: '#' },
    { id: 21, title: 'Resume samples', path: '#' },
    { id: 's2', title: 'Find Jobs', path: '#' },
    { id: 's4', title: ' Monthly subscriptions', path: '#' },
    { id: 14, title: 'Finance courses', path: '#' },
    { id: 22, title: 'Job letter samples', path: '#' },
    { id: 4, title: 'Jobs4u', path: '#' },
    { id: 10, title: 'Basic & premium plans', path: '#' },
    { id: 16, title: 'Design courses', path: '#' },
    { id: 10, title: '', path: '#' },
    { id: 5, title: 'Priority applicant', path: '#' },
    { id: 10, title: '', path: '#' },
    { id: 17, title: 'Healthcare courses', path: '#' },
    { id: 10, title: '', path: '#' },
    { id: 1, title: 'Contact us', path: '#' },
    { id: 10, title: '', path: '#' },
    { id: 18, title: 'Degree programs  ', path: '#' },
    { id: 10, title: '', path: '#' },
]

export const Foremployers = [
    { id: 1, title: 'Buy online', path: '#' },
    { id: 2, title: 'Hiring solutions', path: '#' },
    { id: 3, title: 'Employer Login', path: '#' }
]